### PR TITLE
height fixed

### PR DESCRIPTION
**Pull request by raji2004**
i fixed the hieght issue 
pls merge

### CODE REVIEW

**Comment by alesbe** [comment]
Thanks for the PR!

I tried the changes but at least in my case, Im getting scrollbars and the grid is overflowing:

prove

I wanted to adapt the grid to the current size without overflowing the space, it's not a problem if the grid is bigger, but it needs to fit in one window without scrolls

**Comment by alesbe** [comment]
Im still getting the scrollbar thing, but if you want I'll merge because of the effort, also the result is good

Thanks for the contribution, happy hacktoberfest!

**Comment by raji2004** [comment]
> Im still getting the scrollbar thing, but if you want I'll merge because of the effort, also the result is good
> 
> Thanks for the contribution, happy hacktoberfest!

thanks

**Comment by raji2004** [comment]
> > Im still getting the scrollbar thing, but if you want I'll merge because of the effort, also the result is good
> > Thanks for the contribution, happy hacktoberfest!
> 
> thanks

i will keep trying sha if i succeed  how do i contact u?

**Pull request merged**
